name: Sync to Hugging Face
on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to Hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git push https://schoi2032:$HF_TOKEN@huggingface.co/spaces/schoi2032/AxiomAI main
