name: Deploy Website
on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: MY_NEW_SECRET
        run: |

      - name: Deploy to GitHub Pages
